# Generated by Django 3.0.3 on 2020-02-26 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200227_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='poll_choice',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/choice'),
        ),
    ]
