# Generated by Django 3.0.3 on 2020-03-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20200229_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-end_date']},
        ),
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
