# Generated by Django 3.0.3 on 2020-03-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20200308_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
